class ColumnException( Exception ): ...
class LineException  ( Exception ): ...


class ColumnDoesntExists        ( ColumnException ): ...
class CantGetColumnNameFromScope( ColumnException ): ...
class LineWrongAttributeType    ( LineException   ): ...